### ISSUE TITLE
Make charts responsive.

### ISSUE THREAD

**Issue by okal** [onaio/vega-viewer#24]
**TODO**
- [ ] Store vega view in vega-viewer component internal state for updates.
- [ ] Add resize event listener.
- [ ] Associate the new container dimensions with the vega spec.

**Comment by okal** [comment]
The last time I had to do this for a library was with Plottable. The approach that tends to work well is to rely on the `window.onresize` event and then reading the dimensions of the bounding element, passing those to the chart object and re rendering it. That's likely the approach I'll take here.

Looking at approaches taken by other libraries:

It's not very clear how the approach taken by C3 works. It seems to be binding to the `window.onresize` event as you'd expect, but I can't tell from the code what the event handler does. This is because the built in event handlers are body-less functions. i.e. `config.onresize` and `config.onresized` are both just 

``` javascript
function() {};
```

Chart.js seems to have a more accessible model

https://github.com/nnnick/Chart.js/blob/cf767f71a24532f63ea7da73fee02bcd65c06a2e/src/Chart.Core.js#L931

Still looking for how it's bound to the resize event though.

**Comment by okal** [comment]
Also looking at Stickshift in a bit since it's built on Vega and is responsive.

**Comment by okal** [comment]
Stickshift reminded me that I'd need to remove the event listener when unmounting.

https://github.com/tmcw/stickshift/blob/b5f90e4f1a7536a32bc9a2f8723f32982f4e0f31/src/components/rows.js#L16

This looks like the approach to take, given the number of similarities. i.e. use of Vega/React.

**Comment by okal** [comment]
This MDN article has proved useful to me more than a few times: https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model/Determining_the_dimensions_of_elements

**Comment by okal** [comment]
Intercepting window.onresize works well. Only problem is that it also affects charts that have display: none, and they end up being resized to nothing basically.
